PRODUCT_PACKAGES += \
	HardwareOverlayPicker \
	QtiAudio \
	TrebleApp \
	treble-overlay-caf-ims \
	treble-overlay-devinputjack \
	treble-overlay-highpriomisc \
	treble-overlay-hw-ims \
	treble-overlay-misc-aod \
	treble-overlay-misc-aod-systemui \
	treble-overlay-misc-dt2w \
	treble-overlay-misc-minimal-brightness \
	treble-overlay-mtk-ims \
	treble-overlay-NavBar \
	treble-overlay-NightMode \
	treble-overlay-realme-c21y \
	treble-overlay-sec-ims \
	treble-overlay-sprd-ims \
	treble-overlay-SystemUI-FalseLocks \
	treble-overlay-telephony-caf-ims \
	treble-overlay-telephony-hw-ims \
	treble-overlay-Telephony-LTE \
	treble-overlay-telephony-mtk-ims \
	treble-overlay-telephony-slsi-ims \
	treble-overlay-telephony-sprd-ims \
	treble-overlay-tethering \
	treble-overlay-tethering-nobpf \
	treble-overlay-wifi5g \

